jobs:
  - job: Lint
    timeoutInMinutes: 10
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          cd script
          npm install --ci
        displayName: Install script dependencies
      - script: script/lint
        displayName: Run linter
